name: "litellm"

networks:
  litellm-net:
    driver: bridge

services:
  ghc-proxy:
    image: litellm/litellm:v1.81.14-stable
    container_name: litellm-proxy-lite
    restart: unless-stopped
    ports:
      - "127.0.0.1:4000:4000"
    environment:
      - LOG_LEVEL=DEBUG
      - ENABLE_NETWORK_MONITOR=true
      - DOCS_URL=/docs
      - ROOT_REDIRECT_URL=/ui
    env_file:
      - .env
    volumes:
      - ./conf/copilot-config.yaml:/app/copilot-config.yaml
      - ./litellm-data:/root/.config/litellm
    command: ["--config", "/app/copilot-config.yaml", "--port", "4000"]
   networks:
      - litellm-net


